/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author 069949345
 */
public class BookInfoScreen2 extends javax.swing.JFrame {

    /**
     * Creates new form BookInfoScreen2
     */
    public BookInfoScreen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        putAuthorNameHere = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        averageRatingLabel = new javax.swing.JLabel();
        putPublicationDateHere = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ratingsList = new javax.swing.JTextArea();
        publisherLabel = new javax.swing.JLabel();
        putPublisherNameHere = new javax.swing.JLabel();
        putAverageRatingHere = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        addReviewButton = new javax.swing.JButton();
        putGenreHere = new javax.swing.JLabel();
        readingLevelLabel = new javax.swing.JLabel();
        putBookCoverHere = new javax.swing.JLabel();
        putReadingLabelHere = new javax.swing.JLabel();
        putTitleHere = new javax.swing.JLabel();
        synopsisLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        putSynopsisHere = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        putAuthorNameHere.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        putAuthorNameHere.setText("jLabel4");

        genreLabel.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        genreLabel.setText("Genre:");

        averageRatingLabel.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        averageRatingLabel.setText("Average Rating:");

        putPublicationDateHere.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        putPublicationDateHere.setText("jLabel6");

        ratingsList.setColumns(20);
        ratingsList.setRows(5);
        jScrollPane2.setViewportView(ratingsList);

        publisherLabel.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        publisherLabel.setText("Publisher:");

        putPublisherNameHere.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        putPublisherNameHere.setText("jLabel8");

        putAverageRatingHere.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        putAverageRatingHere.setText("jLabel15");

        dateLabel.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        dateLabel.setText("Date of Publication:");

        addReviewButton.setText("Add Rating/Review");

        putGenreHere.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        putGenreHere.setText("jLabel10");

        readingLevelLabel.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        readingLevelLabel.setText("Reading Level:");

        putReadingLabelHere.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        putReadingLabelHere.setText("jLabel12");

        putTitleHere.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        putTitleHere.setText("Title goes here");

        synopsisLabel.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        synopsisLabel.setText("Synopsis:");

        authorLabel.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        authorLabel.setText("Author:");

        putSynopsisHere.setEditable(false);
        putSynopsisHere.setColumns(20);
        putSynopsisHere.setLineWrap(true);
        putSynopsisHere.setRows(5);
        putSynopsisHere.setWrapStyleWord(true);
        putSynopsisHere.setOpaque(false);
        jScrollPane1.setViewportView(putSynopsisHere);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(putBookCoverHere, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(putTitleHere, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(authorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(putAuthorNameHere))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateLabel)
                                        .addGap(10, 10, 10)
                                        .addComponent(putPublicationDateHere))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(publisherLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(putPublisherNameHere))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(genreLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(putGenreHere))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(readingLevelLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(putReadingLabelHere))
                                    .addComponent(synopsisLabel))
                                .addGap(0, 77, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(averageRatingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(putAverageRatingHere)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addReviewButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(putTitleHere, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorLabel)
                            .addComponent(putAuthorNameHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(putPublicationDateHere)
                            .addComponent(dateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publisherLabel)
                            .addComponent(putPublisherNameHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genreLabel)
                            .addComponent(putGenreHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(readingLevelLabel)
                            .addComponent(putReadingLabelHere))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(synopsisLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(putBookCoverHere, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(averageRatingLabel)
                    .addComponent(putAverageRatingHere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addReviewButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookInfoScreen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReviewButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel averageRatingLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel publisherLabel;
    private javax.swing.JLabel putAuthorNameHere;
    private javax.swing.JLabel putAverageRatingHere;
    private javax.swing.JLabel putBookCoverHere;
    private javax.swing.JLabel putGenreHere;
    private javax.swing.JLabel putPublicationDateHere;
    private javax.swing.JLabel putPublisherNameHere;
    private javax.swing.JLabel putReadingLabelHere;
    private javax.swing.JTextArea putSynopsisHere;
    private javax.swing.JLabel putTitleHere;
    private javax.swing.JTextArea ratingsList;
    private javax.swing.JLabel readingLevelLabel;
    private javax.swing.JLabel synopsisLabel;
    // End of variables declaration//GEN-END:variables
}
