/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Engine.Book;
import Engine.Library;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author North Star Inc. Team
 */

public class BookInfoScreen extends javax.swing.JFrame {

    private Library lib = new Library();
    private Book b;

    public BookInfoScreen() {
        initComponents();
    }

    public BookInfoScreen(String url) {
        initComponents();
        //sets labels to book info respectively
        b = lib.getBookInfo(url);
        jTitleLabel.setText(b.getTitle());
        jAuthorLabel.setText(b.getAuthor());
        jDatePubLabel.setText(b.getDatePublished());
        jPubLabel.setText(b.getPublisher());
        jGenreLabel.setText(b.getCategories());
        putSynopsisHere.setText(b.getSynopsis());
        //gets book cover image
        Image temp = null;
        try {
            temp = ImageIO.read(new URL(getB().getCover()));
            temp = temp.getScaledInstance(jCoverLabel.getWidth(), jCoverLabel.getHeight(), Image.SCALE_SMOOTH);
        } catch (IOException e) {
            e.printStackTrace();
        }
        jCoverLabel.setIcon(new ImageIcon(temp));
        //puts book comments into comment section
        putAverageRatingHere.setText(String.format("%.2f", b.getAverageRating()));
        String[] comments = b.getComments();
        String[] ratings = b.getRatings();
        String[] ids = b.getIds();
        String s = "";
        for (int i = 0; i < comments.length; i++) {
            s += ids[i] + "\tRating: " + ratings[i] + "\n" + comments[i] + "\n\n";
        }
        ratingsList.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCoverLabel = new javax.swing.JLabel();
        jTitleLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jAuthorLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDatePubLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPubLabel = new javax.swing.JLabel();
        putAverageRatingHere = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ratingAndReviewButton = new javax.swing.JButton();
        jGenreLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        putSynopsisHere = new javax.swing.JTextArea();
        averageRatingLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ratingsList = new javax.swing.JTextArea();
        backToLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jTitleLabel.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        jTitleLabel.setText("Title goes here");
        jTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel3.setText("Author:");

        jAuthorLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jAuthorLabel.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel5.setText("Genre:");

        jDatePubLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jDatePubLabel.setText("jLabel6");

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel7.setText("Publisher:");

        jPubLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jPubLabel.setText("jLabel8");

        putAverageRatingHere.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        putAverageRatingHere.setText("jLabel15");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel9.setText("Date of Publication:");

        ratingAndReviewButton.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        ratingAndReviewButton.setText("Add Rating/Review");
        ratingAndReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingAndReviewButtonActionPerformed(evt);
            }
        });

        jGenreLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        jGenreLabel.setText("jLabel10");

        jLabel13.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        jLabel13.setText("Synopsis:");

        putSynopsisHere.setEditable(false);
        putSynopsisHere.setColumns(20);
        putSynopsisHere.setLineWrap(true);
        putSynopsisHere.setRows(5);
        putSynopsisHere.setToolTipText("");
        putSynopsisHere.setWrapStyleWord(true);
        putSynopsisHere.setOpaque(false);
        jScrollPane1.setViewportView(putSynopsisHere);

        averageRatingLabel.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        averageRatingLabel.setText("Average Rating:");

        ratingsList.setEditable(false);
        ratingsList.setColumns(20);
        ratingsList.setRows(5);
        jScrollPane2.setViewportView(ratingsList);

        backToLogin.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        backToLogin.setText("Back to Login");
        backToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAuthorLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(10, 10, 10)
                                .addComponent(jDatePubLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPubLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jGenreLabel))
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(averageRatingLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(putAverageRatingHere)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToLogin)
                .addGap(18, 18, 18)
                .addComponent(ratingAndReviewButton)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jAuthorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDatePubLabel)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jPubLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jGenreLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jCoverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(averageRatingLabel)
                    .addComponent(putAverageRatingHere))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToLogin)
                    .addComponent(ratingAndReviewButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Brings user to ReviewScreen in order to write a review
     * @param evt 
     */
    private void ratingAndReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingAndReviewButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        //gets book info url in order to store comments
        new ReviewScreen(getB().getUrl()).setVisible(true);
    }//GEN-LAST:event_ratingAndReviewButtonActionPerformed

    /**
     * Brings user to LoginScreen in order to search for another book and enter student id
     * @param evt 
     */
    private void backToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_backToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookInfoScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookInfoScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel averageRatingLabel;
    private javax.swing.JButton backToLogin;
    private javax.swing.JLabel jAuthorLabel;
    private javax.swing.JLabel jCoverLabel;
    private javax.swing.JLabel jDatePubLabel;
    private javax.swing.JLabel jGenreLabel;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jPubLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jTitleLabel;
    private javax.swing.JLabel putAverageRatingHere;
    private javax.swing.JTextArea putSynopsisHere;
    private javax.swing.JButton ratingAndReviewButton;
    private javax.swing.JTextArea ratingsList;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lib
     */
    public Library getLib() {
        return lib;
    }

    /**
     * @param lib the lib to set
     */
    public void setLib(Library lib) {
        this.lib = lib;
    }

    /**
     * @return the b
     */
    public Book getB() {
        return b;
    }

    /**
     * @param b the b to set
     */
    public void setB(Book b) {
        this.b = b;
    }
}
