package GUI;

import Engine.Book;
import Engine.Library;

/**
 *
 * @author North Star Inc. Team
 */
public class ReviewScreen extends javax.swing.JFrame {
    //Library class handles book info
    private Library lib;
    //bookinfo url
    private String url;
    //updates book info
    private Book b;
    public static String id;
    
    public ReviewScreen() {
        initComponents();
    }
    public ReviewScreen(String url){
        initComponents();
        lib = new Library();
        b = lib.getBookInfo(url);
        this.url = url;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterReviewHere = new javax.swing.JTextArea();
        ratingLabel = new javax.swing.JLabel();
        enterStarNumberHere = new javax.swing.JTextField();
        starsLabel = new javax.swing.JLabel();
        reviewLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        backToLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enterReviewHere.setColumns(20);
        enterReviewHere.setRows(5);
        jScrollPane1.setViewportView(enterReviewHere);

        ratingLabel.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        ratingLabel.setText("Rating:");

        starsLabel.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        starsLabel.setText("Stars");

        reviewLabel.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        reviewLabel.setText("Review:");

        backButton.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        doneButton.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        doneButton.setText("Done");
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        backToLogin.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        backToLogin.setText("Log In Again");
        backToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reviewLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ratingLabel)
                        .addGap(18, 18, 18)
                        .addComponent(enterStarNumberHere, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(starsLabel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doneButton)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratingLabel)
                    .addComponent(enterStarNumberHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(starsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reviewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(doneButton)
                    .addComponent(backToLogin))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Brings user back to BookInfoScreen
     * @param evt 
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new BookInfoScreen(getUrl()).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * Brings user back to BookInfoScreen with comment section updated
     * @param evt 
     */
    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        getB().writeReview(enterReviewHere.getText(),Integer.parseInt(enterStarNumberHere.getText()),id);
        this.dispose();
        new BookInfoScreen(getUrl()).setVisible(true);
    }//GEN-LAST:event_doneButtonActionPerformed
    /**
     * Allows user to return to login screen and change student id
     * @param evt 
     */
    private void backToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginScreen().setVisible(true);
    }//GEN-LAST:event_backToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton backToLogin;
    private javax.swing.JButton doneButton;
    private javax.swing.JTextArea enterReviewHere;
    private javax.swing.JTextField enterStarNumberHere;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ratingLabel;
    private javax.swing.JLabel reviewLabel;
    private javax.swing.JLabel starsLabel;
    // End of variables declaration//GEN-END:variables

    
    //GETTERS AND SETTERS
    
    /**
     * @return the lib
     */
    public Library getLib() {
        return lib;
    }

    /**
     * @param lib the lib to set
     */
    public void setLib(Library lib) {
        this.lib = lib;
    }

    /**
     * @return the url
     */
    public String getUrl() {
        return url;
    }

    /**
     * @param url the url to set
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * @return the b
     */
    public Book getB() {
        return b;
    }

    /**
     * @param b the b to set
     */
    public void setB(Book b) {
        this.b = b;
    }
}
