/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SierpinskiTriangle;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.Timer;

/**
 *
 * @author 349361337
 */
public class DrawingArea extends javax.swing.JPanel {

    public int x;
    public int y;
    public int depth = 5;
    public int side = 200;
    /**
     * Creates new form Sierpinski
     */
    public DrawingArea() {
        initComponents();
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        x = this.getWidth()/2-side/2;
        y = this.getHeight()/2+side/2;
        int[] xCord = {x,x+side/2,x+side};
        int height = (int)((side/2)*Math.tan(Math.PI/3));
        int[] yCord = {y,y-height,y};
        g.drawPolygon(xCord,yCord,3);
        drawTriangle(g,x+side/4,y-height/2,depth,side/2);
    }
    
    public void drawTriangle(Graphics g,int x,int y,int depth, int side){
        if(depth==0) return;
        int[] xCord = {x,x+side/2,x+side};
        int height = (int)((side/2)*Math.tan(Math.PI/3));
        int[] yCord = {y,y+height,y};
        g.drawPolygon(xCord,yCord,3);
        drawTriangle(g,x+side/4,y-height/2,--depth,side/2);
        //drawTriangle(g,x+side/2,y-height/2,--depth,side/2);
    }
    
    private class TimerListener implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e){
            repaint();
        }
    }
    
    public void anim(){
        Timer t = new Timer(1000,new TimerListener());
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
